### ISSUE TITLE
having issues...

### ISSUE THREAD

**Issue by JLaw0351** [joelverhagen/TorSharp#17] opened 2017-07-28 19:51 UTC
Hi guys, I feel like a total dolt. I installed the torsharp nuget into my project in c#, I have installed privoxy, and tor expert bundle, create a c# console app in framework 4.5.2 and have just not been able to get the  await new TorSharpToolFetcher(settings, new HttpClient()).FetchAsync();  to give me anything but an "object reference not set to instance" issue.  Maybe I should just be able to figure this out but there is zero doc on line unfortunately on whether i need to do any further config straight out of the box. I ran the sample and it is just not working for me. I was able to get the ZippedToolsDirectory to populate the privoxy zip, but the ExtractedToolsDirectory I am unclear about what I point that to. I am OK not reloading the latest privoxy and tor each time it loads...   Something must be hosed in my environment to use the sample. HELP.,... first time in 15 years I have asked a question on line like this. Thanks for a kickstart. I am an idiot...

**Comment by kerryjiang** [comment] 2017-07-28 19:59
Should be duplicate issue with this one https://github.com/joelverhagen/TorSharp/issues/16

**Comment by JLaw0351** [comment] 2017-07-28 21:16
await proxy.ConfigureAndStartAsync();

this is where it is bombing out now after removing the directory properties in the settings instantiation and removing the download tools fetcher line...

**Comment by kerryjiang** [comment] 2017-07-28 21:18
You don't need remove the directory properties. Because the previous version Tor was downloaded into that directories. If you remove it, the application will search the Tor in other places.

**Comment by JLaw0351** [comment] 2017-07-28 22:25
await proxy.ConfigureAndStartAsync();  still bombing out. tor exe is definitely sitting there in programs 86 installed just ready to be accessed. do i need to make privoxy config issues or anything to get this to run?

**Comment by joelverhagen** [comment] 2017-07-29 02:34
@JLaw0351 -- you're not an idiot 😃. This is side project quality code. Null reference exceptions are not at all helpful to users!!! I am working on a fix as we speak. This is indeed a duplicate of https://github.com/joelverhagen/TorSharp/issues/16.

**Closed by joelverhagen** 2017-07-29 02:34 UTC
