### ISSUE TITLE
how to use a bridge (obfs4 or snowflake) when config tor

### ISSUE THREAD

**Issue by kitoytimmy** [joelverhagen/TorSharp#84] opened 2021-10-18 06:22 UTC
how to use a bridge (obfs4 or snowflake) when config tor

**Comment by joelverhagen** [comment] 2021-12-12 07:32
Hey @kitoytimmy, I don't know much about Tor bridges, but perhaps look at this issue and the linked PR? Another person was interested in the same thing and it appears that they are not unblocked: https://github.com/joelverhagen/TorSharp/issues/48

**Comment by joelverhagen** [comment] 2021-12-12 23:05
Closing since this appears as a duplicate of #48. Feel free to open a new issue if you see a feature gap.

**Closed as completed by joelverhagen** 2021-12-12 23:05 UTC
Labels: question
